# Generated by Django 5.1.7 on 2026-02-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en el menú')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stadiums/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('is_rival', models.BooleanField(default=True, help_text='Marcar si es un equipo rival')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='squads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.category')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sport.squad')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('HC', 'Head Coach'), ('AC', 'Assistant Coach'), ('FT', 'Fitness Coach'), ('MD', 'Medic/Physio'), ('KM', 'Kitman')], max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='sport.squad')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('home_goals', models.PositiveIntegerField(default=0)),
                ('away_goals', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('LIV', 'Live'), ('FIN', 'Finished'), ('SUS', 'Suspended')], default='SCH', max_length=3)),
                ('report', models.TextField(blank=True, help_text='Crónica o resumen del partido')),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.stadium')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='sport.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='sport.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.tournament')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
