# Generated by Django 5.1.7 on 2026-02-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='name',
        ),
    ]
