# Generated by Django 5.1.7 on 2026-02-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_remove_squad_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='squad',
            options={'verbose_name': 'Plantel', 'verbose_name_plural': 'Planteles'},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'verbose_name': 'Estadio', 'verbose_name_plural': 'Estadios'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Cuerpo Técnico', 'verbose_name_plural': 'Cuerpo Técnico'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Torneo', 'verbose_name_plural': 'Torneos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden de aparición en el menú', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Goles Visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='sport.team', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Goles Local'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='sport.team', verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='match',
            name='report',
            field=models.TextField(blank=True, help_text='Resumen del partido', verbose_name='Crónica'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.stadium', verbose_name='Estadio'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCH', 'Programado'), ('LIV', 'En Juego'), ('FIN', 'Finalizado'), ('SUS', 'Suspendido')], default='SCH', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.tournament', verbose_name='Torneo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dorsal'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apodo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Arquero'), ('DEF', 'Defensor'), ('MID', 'Mediocampista'), ('FWD', 'Delantero')], max_length=3, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='player',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sport.squad', verbose_name='Plantel'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='squads/', verbose_name='Foto Grupal'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='season',
            field=models.CharField(max_length=50, verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stadiums/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('HC', 'Director Técnico'), ('AC', 'Ayudante de Campo'), ('FT', 'Preparador Físico'), ('MD', 'Médico/Kinesiólogo'), ('KM', 'Utilero')], max_length=2, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='sport.squad', verbose_name='Plantel'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_rival',
            field=models.BooleanField(default=True, help_text='Marcar si es un equipo rival', verbose_name='Es Rival'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Escudo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.CharField(blank=True, max_length=50, verbose_name='Temporada'),
        ),
    ]
