# Generated by Django 5.1.7 on 2026-02-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('sport', '0003_alter_category_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['order'], 'verbose_name': 'Directivo', 'verbose_name_plural': 'Comisión Directiva'},
        ),
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'verbose_name': 'Álbum de Fotos', 'verbose_name_plural': 'Galería de Fotos'},
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Foto de Galería', 'verbose_name_plural': 'Fotos de Galería'},
        ),
        migrations.AlterModelOptions(
            name='historyevent',
            options={'ordering': ['year'], 'verbose_name': 'Hito Histórico', 'verbose_name_plural': 'Historia del Club'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='order',
            field=models.PositiveIntegerField(default=99, verbose_name='Orden Jerárquico'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='period',
            field=models.CharField(blank=True, help_text='Ej: 2024-2028', max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='board/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover',
            field=models.ImageField(upload_to='gallery_covers/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='club.galleryalbum', verbose_name='Álbum'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='history/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(upload_to='news/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publicada'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='news',
            name='related_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.match', verbose_name='Partido Relacionado'),
        ),
        migrations.AlterField(
            model_name='news',
            name='related_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.player', verbose_name='Jugador Relacionado'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(help_text='Breve resumen', max_length=300, verbose_name='Bajada'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
